
version: 2

models:
  - name: int_exchanges
    description: data on home/apartment exchanges. 
    docs:
      show: true
      node_color: blue
    columns:
      - name: conversation_id
        description: Primary key identifier of customer orders
        tests:
          - not_null

      - name: exchange_id
        description: user_id of the person initiating the exchange

      - name: created_at
        description: date of creation of the conversation (=exchange request)
      
      - name: creator_id
        description: user_id of the person initiating the exchange

      - name: guest_user_id
        description: user_id of the person initiating the exchange

      - name: host_user_id
        description: user_id of the person initiating the exchange

      - name: finalized_at
        description: date when the exchange was finalized (if null, it means that the exchange request was not successful)

      - name: canceled_at
        description: date when the finalized exchange has been cancelled

      - name: start_on
        description: date when the exchange starts (can be filled in even if the exchange is not finalized. It corresponds to the requested dates)

      - name: end_on
        description: date when the exchange ends (can be filled in even if the exchange is not finalized. It corresponds to the requested dates)

      - name: guest_countguest_count
        description: number of people coming

      - name: night_count
        description: number of nights of the exchange

      - name: user_cancellation_id
        description: user_id who canceled

      - name: exchange_type
        description: via Guest Points or reciprocal if the exchange is reciprocal, only one conversation is created (via the creator_id we know who initiated the request), but two exchanges are created

      - name: home_type
        description: house or appartment

      - name: residence_type
        description: main or secondary house

      - name: capacity
        description: maximum number of people who can come

      - name: country
        description: host house country

      - name: city
        description: host house city

  - name: int_subscriptions
    description: Sample of subscriptions since 2019 (particular context in 2020/2021). If renew = 1 , you will find the subscription line and the renewal line for the next year
    docs:
      show: true
      node_color: red
    columns:
      - name: subscription_date
        description: YYYY-MM-DD date format of the subscription start date
        tests:
          - not_null

      - name: user_id
        description: ID of the owner of the subscription
        tests:
          - not_null

      - name: renew
        description: did the user re-subscribe the following year (the month of the expiration of his subscription)

      - name: first_subscription_date	
        description: date of the users first subscription YYYY-MM-DD

      - name: first_subscription
        description: index of the distinct product within the order

      - name: referral
        description: 1 if the user has been sponsored

      - name: promotion
        description: 1 if the user had a promotion for his subscription

      - name: payment3x
        description: 1 if the user has used the 3x payment to subscribe

      - name: payment2
        description: 1 if the user has paid his 2nd payment

      - name: payment3
        description: 1 if the user has paid his 3rd payment

      - name: country
        description: user country

      - name: city
        description: user city


  - name: int_guest_exg
    description: aggregation of exchange data on a guest user_id level
    docs:
      show: true
      node_color: orange
    columns:
      - name: guest_id
        description: user id of the guest in the exchange
      - name: nb_reqst
        description: the amount of exchanges where this user is the guest
      - name: first_reqst
        description: the date of the first request in our dataset where this user is the guest
      - name: last_reqst
        description: the date of the last request in our dataset where this user is the guest
      - name: nb_nights_reqst
        description: the number of nights requested where this user ID is the guest
      - name: avg_nights_count
        description: the avg number of nights of requests where this user ID is the guest
      - name: nb_exg_not_finalized
        description: number of exchanges made where this user is the guest which weren`t finalized
      - name: nb_exg_finalized_not_cancelled
        description: number of exchanges made where this user is the guest which were finalized and successful 
      - name: nb_exg_finalized_cancelled
        description: number of exchanges made where this user is the guest which were finalized but then cancelled
      - name: nb_non_reciprocal_exg
        description: number of exchanges initiated which were non-reciprocal
      - name: nb_reciprocal_exg
        description: number of exchanges initiated which were reciprocal
      - name: min_capacity
        description: the lowest capacity requested
      - name: max_capacity
        description: the highest capacity requested
      - name: avg_capacity
        description: the avg capacity requested
      - name: nb_cities
        description: number of different cities requested



  - name: int_host_exg
    description: aggregation of exchange data on a host user_id level
    docs:
      show: true
      node_color: orange
    columns:
      - name: host_id
        description: user id of the host in the exchange
      - name: nb_reqst
        description: the amount of exchanges where this user is the host
      - name: first_reqst
        description: the date of the first request in our dataset where this user is the host
      - name: last_reqst
        description: the date of the last request in our dataset where this user is the host
      - name: nb_nights_reqst
        description: the number of nights requested where this user ID is the host
      - name: avg_nights_count
        description: the avg number of nights of requests where this user ID is the host
      - name: nb_exg_not_finalized
        description: number of exchanges made where this user is the host which weren`t finalized
      - name: nb_exg_finalized_not_cancelled
        description: number of exchanges made where this user is the host which were finalized and successful 
      - name: nb_exg_finalized_cancelled
        description: number of exchanges made where this user is the host which were finalized but then cancelled
      - name: nb_non_reciprocal_exg
        description: number of exchanges initiated which were non-reciprocal
      - name: nb_reciprocal_exg
        description: number of exchanges initiated which were reciprocal
      - name: min_capacity
        description: the lowest capacity requested
      - name: max_capacity
        description: the highest capacity requested
      - name: avg_capacity
        description: the avg capacity requested
      - name: nb_cities
        description: number of different cities requested